### ISSUE TITLE
Uncaught (in promise) TypeError: t.getStreamData

### ISSUE THREAD

**Issue by maltsaar** [thelevicole/youtube-to-html5-loader#28]
Hi,

For some reason even the example in github pages doesn't seem to work for me.
I have tried setting up my own instance with the provided [youtube-to-html5-server](https://github.com/thelevicole/youtube-to-html5-server) but I get the same error.

Any idea what I could try?

![image](https://user-images.githubusercontent.com/6921039/182950593-9a976863-c3d0-4951-952a-369e93da564f.png)

**Comment by ariskuckovic-abtion** [comment]
I have the same issue.

**Comment by davidfurlong** [comment]
yeah this lib is broken/discontinued it seems

**Comment by vaibhavsharma1234** [comment]
what is the solution to it
i want to fetch videos from youtube and play it 
i am not getting any solution for it

**Comment by ariskuckovic-abtion** [comment]
@vaibhavsharma1234 

I'm not sure going to get a solution for this.
Looks like it's discontinued.

**Comment by blackundo** [comment]
[[[[[> what is the solution to it i want to fetch videos from youtube and play it i am not getting any solution for it

version 5 is broken, u can switch to ver4 
is link cdn: https://cdn.jsdelivr.net/gh/thelevicole/youtube-to-html5-loader@4.0.1/dist/YouTubeToHtml5.js

**Comment by vaibhavsharma1234** [comment]
this is also not working 
any other solution
YouTubeToHtml5.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'streamingData')
    at YouTubeToHtml5.parseYoutubeMeta (YouTubeToHtml5.js:1:4584)
    at YouTubeToHtml5.js:1:6023

**Comment by JKDos** [comment]
I see the same error, but it works to get the video. It's playable, and it's downloadable. I cannot figure out though how to ensure it's 1080p. Setting it in the constructor crashes the script.

**Comment by natsu90** [comment]
following @blackundo advice, i switched to version 4.0.1, but i get a different error. i figured it is due to dead `yt2html5.com` server. so i run `youtube-to-html5-server` locally, then run the code as below;

    const controller = new YouTubeToHtml5({
      autoload: false
    });

    controller.addFilter('api.endpoint', function(url) {
      return url.replace('https://yt2html5.com', 'http://localhost:8000');
    });

    controller.load();

but i still can not get it to run due to 403 error when trying to stream from the Youtube direct URL.
