### ISSUE TITLE
Script Broke - Cannot read properties of undefined (reading 'streamingData')

### ISSUE THREAD

**Issue by studiofruits** [thelevicole/youtube-to-html5-loader#34]
I was working a few days ago, now I get this error:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'streamingData')
    at YouTubeToHtml5.parseYoutubeMeta (YouTubeToHtml5.js:1:4584)
    at YouTubeToHtml5.js:1:6023`

**Comment by blalmal10a** [comment]
will it be fixed anytime soon? Imagine some people rely their application on this html5 player xD
