### ISSUE TITLE
Script broke! Any suggestions for fix please?

### ISSUE THREAD

**Issue by Christof0007** [thelevicole/youtube-to-html5-loader#35]
Using your example page:

https://thelevicole.com/youtube-to-html5-loader/#examples

Google Chrome console error:

YouTubeToHtml5.js:1 Uncaught (in promise) TypeError: t.getStreamData is not a function
at o.value (YouTubeToHtml5.js:1:7025)
at YouTubeToHtml5.js:1:3287
at Array.forEach ()
at o.value (YouTubeToHtml5.js:1:3255)
at YouTubeToHtml5.js:1:6788

**Does not work on either Chrome or Firefox**

**Comment by phettler** [comment]
I'm also seeing this using Edge.  Any update on if/when this will be fixed please?
